guardian/live-app-versions

build.sbt
project/build.properties
project/plugins.sbt
src/main/resources/log4j2.xml
src/main/scala/com/gu/liveappversions/AccessToken.scala
src/main/scala/com/gu/liveappversions/Config.scala
src/main/scala/com/gu/liveappversions/Lambda.scala

* Adds functionality for creating tokens to authenticate with App Store Connect API - borrowed from @NathanielBennett's implementation here: https://github.com/guardian/ophan-data-lake/blob/master/data-lake-lambdas/mobile-ingestion/src/main/scala/com/gu/itunes/jwt/JwtTokenBuilder.scala
* Adds logic for finding the latest version which has been released to external testers - this is essentially a Scala implementation of https://deliveroo.engineering/2019/12/10/testflight-app-store-connect-api.html (I've re-written this because Ruby is not well-supported by our tooling and most engineers here - myself included - will feel more confident maintaining a Scala project).
* Todo: unit tests, error handling, monitoring/alerts, writing to persistent storage, infrastructure as code, riff-raff config …

Add basic logic for finding the latest beta version for an iOS app

---

build.sbt
cfn.yaml
riff-raff.yaml
src/main/scala/com/gu/liveappversions/AccessToken.scala
src/main/scala/com/gu/liveappversions/Config.scala
src/main/scala/com/gu/liveappversions/Lambda.scala
src/test/scala/com.gu.liveappversions.integration/IntegrationTest.scala

* Sets up the infrastructure 
* Makes the project deployable using RiffRaff
* Reads private credentials from parameter store (instead of environment variables)
* Moves the local runner to `src/test` (to keep the main application code tidy)

Deploy lambda to AWS using RiffRaff

---

build.sbt
cfn.yaml
src/main/scala/com/gu/liveappversions/AppStoreConnectApi.scala
src/main/scala/com/gu/liveappversions/Aws.scala
src/main/scala/com/gu/liveappversions/BuildOutput.scala
src/main/scala/com/gu/liveappversions/Config.scala
src/main/scala/com/gu/liveappversions/Lambda.scala
src/main/scala/com/gu/liveappversions/S3Uploader.scala
src/test/scala/com.gu.liveappversions.integration/IntegrationTest.scala
src/test/scala/com/gu/liveappversions/BuildOutputTest.scala

* Adds code for uploading JSON files to S3
* Adds IAM permissions to allow the lambda to upload to S3
* Surfaces information about the last few builds (instead of just the most recent one) because [some clients](https://github.com/guardian/data-lake-alerts) will need this history.
* Adds unit tests for the main logic
* Some minor refactoring

Upload latest build information to S3

---

cfn.yaml

This additional permission is required in order to make objects public. I didn't notice this whilst testing because this piece of functionality is [specific to the PROD lambda](https://github.com/guardian/live-app-versions/blob/master/src/main/scala/com/gu/liveappversions/S3Uploader.scala#L30-L31).

Allow lambda to make object public

---

cfn.yaml

This lambda will [throw an exception](https://github.com/guardian/live-app-versions/blob/master/src/main/scala/com/gu/liveappversions/Lambda.scala#L32) if it fails to update the JSON file stored in S3. 
Individual failures should be tolerated, since the lambda makes a HTTP request to the App Store Connect API and this may occasionally fail. The impact of an individual failure is minor: we will serve stale data for slightly longer than normal. Once the [schedule](https://github.com/guardian/live-app-versions/blob/master/cfn.yaml#L88) is enabled, temporary problems should resolve themselves without human intervention. 
Consequently this alert should only fire if there are consistent failures (as these may indicate long-term or permanent problems - e.g. revoked API key or bug in our codebase …

Add alert for consistent failures

---

cfn.yaml

Now that the major functionality is [working](https://mobile.guardianapis.com/static/reserved-paths/ios-live-app/recent-beta-releases.json), we should enable the CloudWatch event rule to ensure that the production data in S3 is kept up to date.

Enable polling schedule in production

---

build.sbt

This [commit](https://github.com/guardian/live-app-versions/pull/2/commits/b44959c3b91b153dd1bd2daf447e366767ad6522) was too aggressive 🙈 
It leads to the following error:
`ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...`
This PR introduces a more targetted merge strategy which allows us to keep `Log4j2Plugins.dat`, which is required.

Update merge strategy to fix logging

---

src/main/scala/com/gu/liveappversions/AppStoreConnectApi.scala
src/test/scala/com/gu/liveappversions/BuildOutputTest.scala

Apple provides the `uploadedDate` in PST, so we also convert it to UTC before storing it (since this will be preferable for most clients).

Include build upload time information in JSON file

---

cfn.yaml

The alert added in https://github.com/guardian/live-app-versions/pull/4 did not work as desired. Although it fired correctly in the first instance, it fired relatively frequently during the incident which was quite noisy and annoying. This seemed to happen because a handful of invocations were able to succeed; consequently the alert state kept changing between `OK` and `Alarm`.
This PR improves the alert by monitoring the % of failures for the lambda invocation. The alert will only fire if the error rate is 100% for one hour. If the service temporarily recovers, it will need to subsequently break entirely (for 1 hour) before the alarm fires again. I think that can probably be considered as a new incident, so it seems appropriate to me.
Here's an [example of that …

Improve monitoring

---

cfn.yaml
riff-raff.yaml
src/main/scala/com/gu/appstoreconnectapi/AccessToken.scala
src/main/scala/com/gu/appstoreconnectapi/AppStoreConnectApi.scala
src/main/scala/com/gu/config/Aws.scala
src/main/scala/com/gu/config/Config.scala
src/main/scala/com/gu/iosdeployments/Lambda.scala
src/main/scala/com/gu/liveappversions/BuildOutput.scala
src/main/scala/com/gu/liveappversions/Lambda.scala
src/main/scala/com/gu/liveappversions/S3Uploader.scala
src/test/scala/com.gu.liveappversions.integration/IntegrationTest.scala
src/test/scala/com/gu/liveappversions/BuildOutputTest.scala

I need another lambda which accesses the App Store Connect API. This lambda will be used to automatically distribute builds to external testers (since moving away from TeamCity the iOS Team are having to doing this manually).
Since this project already has most of the code I need, I've restructured it to accommodate a second lambda. I've also added a basic "hello world" lambda just to prove that this all works as expected.
I've tested that the original lambda can still run successfully.

Restructure project to accommodate second lambda

---

src/main/scala/com/gu/appstoreconnectapi/AppStoreConnectApi.scala
src/main/scala/com/gu/appstoreconnectapi/Conversion.scala
src/main/scala/com/gu/config/Config.scala
src/main/scala/com/gu/githubapi/Conversion.scala
src/main/scala/com/gu/githubapi/GitHubApi.scala
src/main/scala/com/gu/iosdeployments/Lambda.scala
src/main/scala/com/gu/liveappversions/BuildOutput.scala
src/main/scala/com/gu/liveappversions/Lambda.scala
src/main/scala/com/gu/okhttp/SharedClient.scala
src/test/scala/com/gu/appstoreconnectapi/ConversionTest.scala
src/test/scala/com/gu/githubapi/ConversionTest.scala
src/test/scala/com/gu/githubapi/GitHubApiTest.scala
src/test/scala/com/gu/iosdeployments/integration/IntegrationTest.scala
src/test/scala/com/gu/liveappversions/BuildOutputTest.scala

**Motivation for adding new functionality:**
iOS deployments are long-running tasks. After uploading builds to App Store Connect, you must (separately) distribute builds to external users. Unfortunately Apple does not provide a webhook (or similar) to notify us when a build becomes ready for distribution, which means that the deployment system must poll whilst waiting for the uploaded build to become ready. The time it takes for a build to become ready for distribution is unpredictable, but it often takes longer than an hour.
Our current solution for iOS deployments uses CI to poll the App Store Connect API whilst waiting for the the build to become ready. This is problematic for two main reasons:
1) We now [pay by the minute for …

Add read-only logic for iOS deployment functionality

---

src/main/scala/com/gu/githubapi/GitHubApi.scala
src/main/scala/com/gu/iosdeployments/Lambda.scala

Follow up to https://github.com/guardian/live-app-versions/pull/12 and https://github.com/guardian/ios-live/pull/5150.
Still to come: distributing builds to external testers automatically.

Add functionality for updating GitHub Deployment status

---

src/main/scala/com/gu/appstoreconnectapi/AppStoreConnectApi.scala
src/main/scala/com/gu/appstoreconnectapi/Conversion.scala
src/main/scala/com/gu/config/Config.scala
src/main/scala/com/gu/iosdeployments/Lambda.scala
src/main/scala/com/gu/okhttp/SharedClient.scala
src/test/scala/com/gu/appstoreconnectapi/ConversionTest.scala
src/test/scala/com/gu/liveappversions/BuildOutputTest.scala

This adds functionality for automatically submitting beta builds for review and distributing them to external testers. 
Follow up to:
https://github.com/guardian/ios-live/pull/5150
https://github.com/guardian/live-app-versions/pull/12
https://github.com/guardian/live-app-versions/pull/14
There will be a final PR after this one to schedule the new lambda regularly and add monitoring/alerting. For now it's been tested by manually re-running the lambda at various points of the deployment cycle.

Automatically submit betas for review and distribute externally

---

cfn.yaml
riff-raff.yaml

Now that the new deployments lambda is [functionally complete](https://github.com/guardian/live-app-versions/pull/15), we want it to poll automatically.

Trigger the deployments lambda on a schedule

---

cfn.yaml

Also tidies up the alert for the live-app-versions lambda and moves debugging tips into a Runbook (Google doc).

Add alert for deployments lambda

---

cfn.yaml
riff-raff.yaml
src/main/scala/com/gu/liveappversions/S3Uploader.scala
src/main/scala/com/gu/liveappversions/android/Lambda.scala
src/main/scala/com/gu/liveappversions/ios/BuildOutput.scala
src/main/scala/com/gu/liveappversions/ios/Lambda.scala
src/test/scala/com.gu.liveappversions.integration/IntegrationTest.scala
src/test/scala/com/gu/liveappversions/BuildOutputTest.scala

* Adds infrastructure for a new lambda function (in support of [this ticket](https://theguardian.atlassian.net/browse/LIVE-422)). Currently this lambda's code doesn't do anything useful; I'll add the logic in a separate PR.
* Moves some iOS-specific code to accommodate the new Android lambda
I've confirmed that this can be [deployed via RiffRaff](https://riffraff.gutools.co.uk/deployment/view/abdb32c7-4a1f-4827-9aa5-aa2467a31a2a). I've also double checked the lambda and alarm configuration via AWS.
* Original iOS lambdas should continue working as before - I'll be able to check this shortly after deployment as both lambdas are triggered on a regular schedule.
* New infrastructure should be deployed successfully.
* Failure alarm has been configured for the new lambda.

Refactor to add basic Android versions lambda

---

cfn.yaml

Improves the alert added in https://github.com/guardian/live-app-versions/pull/20 by adding a link to the appropriate section of our runbook.

Add runbook link to Android alarm

---

README.md

I noticed that the README for this project was quite out of date.

Include information about newer lambdas in the README

---

build.sbt
src/main/scala/com/gu/config/Config.scala
src/main/scala/com/gu/liveappversions/android/Lambda.scala
src/main/scala/com/gu/playdeveloperapi/Conversion.scala
src/main/scala/com/gu/playdeveloperapi/PlayDeveloperApi.scala
src/main/scala/com/gu/playdeveloperapi/Token.scala
src/test/scala/com/gu/playdeveloperapi/ConversionTest.scala

Following on from https://github.com/guardian/live-app-versions/pull/20, this PR adds basic functionality for retrieving version/track information from Google. At the moment the lambda doesn't store the data anywhere useful (it simply logs the result) - I'll add the data storing step in the next PR.
Once deployed to `PROD`, we should see the latest Android build information appearing in the logs.

Add basic functionality for checking Android versions

---

src/main/scala/com/gu/appstoreconnectapi/AppStoreConnectApi.scala
src/main/scala/com/gu/appstoreconnectapi/Conversion.scala
src/main/scala/com/gu/githubapi/GitHubApi.scala
src/main/scala/com/gu/iosdeployments/Lambda.scala
src/test/scala/com/gu/appstoreconnectapi/ConversionTest.scala

This allows us to keep a record of production releases [in GitHub](https://github.com/guardian/ios-live/deployments/activity_log) (I've tested this with `8.37` to confirm that it works).
There's a bit more detail on the motivation for this change here: https://github.com/guardian/ios-live/pull/5326 (tl;dr Apple don't provide the webhooks that we need).

[iosdeployments] Add functionality for tracking new production releases

---

src/main/scala/com/gu/appstoreconnectapi/AppStoreConnectApi.scala
src/main/scala/com/gu/appstoreconnectapi/Conversion.scala
src/main/scala/com/gu/githubapi/GitHubApi.scala
src/main/scala/com/gu/iosdeployments/Lambda.scala

In the following scenario:
1. We submit build A for review
1. We/Apple decide to reject build A
1. We submit build B for review 
1. We release build B
...post-release automation was not being started correctly for build B. This happened because the polling logic was still waiting for build A to become released before moving onto checking build B.
This PR fixes the issue described above by marking the deployment linked to a rejected build as `failed` in [GitHub](https://github.com/guardian/ios-live/deployments/activity_log?environment=production). I've tested this by uploading and rejecting a build.

Handle rejected builds gracefully

---

src/main/scala/com/gu/githubapi/Conversion.scala
src/main/scala/com/gu/githubapi/GitHubApi.scala
src/main/scala/com/gu/iosdeployments/Lambda.scala
src/test/scala/com/gu/githubapi/ConversionTest.scala

We recently had an issue where an iOS beta deployment was cancelled midway through. This created a weird state where the iOS deployments lambda function was polling/waiting for a build to appear in App Store Connect, but the build was never going to show up. Because we only attempt to process [a single beta deployment per lambda invocation](https://github.com/guardian/live-app-versions/blob/main/src/main/scala/com/gu/iosdeployments/Lambda.scala#L88), everything got a bit stuck due to this 🙈 
It was possible for this problem to happen if the upload build script was interrupted whilst executing one of [these tasks](https://github.com/guardian/ios-live/blob/03abcc3e8901f7f6d427d3ffc6410d840ce943b1/GLA/fastlane/Fastfile#L70-L101). An equivalent problem could have affected production …

Handle abandoned iOS deployments

---

src/main/scala/com/gu/iosdeployments/Lambda.scala

From https://github.com/guardian/ios-live/deployments#activity-log we can see that many of the iOS deployments in the last week are still `pending`. We have also observed that our external betas have not been automatically distributed to testers.
From the CloudWatch logs, I can see that we have the message 
``` 
No action was required for beta deployment 18055. Full details are: Some(LiveAppBeta(18055,2f17f9c8-1227-4fe1-932a-f04767c92af3,2021-02-12T10:26:45Z,EXPIRED,EXPIRED))
```
and in AppStoreConnect, I can see that the build 18055 was expired (I believe to avoid confusion, since someone was kicking off lots of internal betas in order to test something).
Because 18055 was expired before the lambda ran, the deployment was not marked as completed, but remained pending indefinitely. The …

Handle expired beta

---

src/main/scala/com/gu/appstoreconnectapi/AppStoreConnectApi.scala

In accordance with https://docs.google.com/document/d/1UslKo11pxv4_xXJsZsxQwjFr5YN0VuqxKu40_IQQPUI/edit?disco=AAAAL0BTYrk, this is a temporary change to only distribute external betas to group 2 (the slightly smaller beta group). We will be be manually distributing builds from an alternative branch to group 1.
We expect to undo this change around the 29th March.
The automated beta will go out soon, and we will double-check which groups it has been distributed to. We are also able to manually trigger this.
If beta is still distributed to both groups: Not the end of the world, we can simply fix and try again with the next automated beta.
If beta is distributed to neither group: Not the end of the world, we can manually add the appropriate group after the fact.

Don't automatically distribute iOS external betas to group 1

---

src/main/scala/com/gu/appstoreconnectapi/AppStoreConnectApi.scala

Reverts guardian/live-app-versions#30 because we have enough data for our test, and would like to go back to releasing builds to both groups.

Revert "Don't automatically distribute iOS external betas to group 1"

---

src/main/scala/com/gu/playdeveloperapi/PlayDeveloperApi.scala

To help debug errors with the Google Developer API response we get, we should add logs to differentiate between the two different responses we recieve.

Add logs to help differentiate between editId and tracks response

---

src/main/scala/com/gu/iosdeployments/Lambda.scala

We [once again](https://github.com/guardian/live-app-versions/pull/29) have multiple pending deployments, this time because one was rejected during beta review. This change should mark that beta deployment as failed, and then go on to process the rest of them normally.
No way to test, except by deploying live, there is no CODE version of App store connect.
The pending deployments in github should be processed.
Low risk.

LIVE-2478: Handle rejected beta deployments

---

build.sbt

Bumps `aws-java-sdk-s3` To v1.12.101.
@frankie297 @ddramowicz any thoughts on the best way to test this still works?
It works the same, but the dependencies are up-to-date.

Bump aws-java-sdk-s3 To v1.12.101

---

build.sbt
project/plugins.sbt

Update log4j dependency to fix security vulnerability - see [doc](https://docs.google.com/document/d/1nVKsXiEXLviHOMY1iQEoyacvN93_SYCQwsOFfaP-dxo)
It also adds a dependency graph plugin so we can run the command `sbt dependencyBrowseTree` which a handy way to quickly view our dependency tree in a browser: https://github.com/sbt/sbt-dependency-graph
Ran tests locally

update log4j version to fix security vulnerability

---

build.sbt

The PR bumps the versions of netty, jackson and okhttp to fix the snyk vulnerabilities.
All test cases passed.  Snyk local scan confirmed the vulnerabilities were fixed.

Bump the versions of netty, jackson and okhttp

---

riff-raff.yaml

From DevX: "Our [recommendations](https://github.com/guardian/recommendations/blob/main/github.md#repository-contents) for repository content suggests not committing S3 bucket names into public repositories."
We can update the riff raff config to remove the s3 bucket name by using the `bucketSsmLookup` property. Given that the deploy bucket already matches the value in `/account/services/artifact.bucket` we don't need to specify an additional ssm param for the bucket name. 
Additionally, `bucketSsmLookup` now defaults to `true`, so this isn't needed either, we can simply omit the `bucket` parameter.

Remove bucket parameter from riff-raff config

---

.github/workflows/build.yml

This PR enables us to build the project using GitHub actions instead of TeamCity. Given TeamCity will be retiring in September 2023 this migration is important.
The new `build` workflow replicates the 2 build steps we see in the existing TeamCity configuration:
- cleans, compiles and tests the project (as well as an extra step to assemble to target jar, which I believe was something previously carried out by the riffRaffUpload command)
- it replaces the `sbt-riffraff-artifact` plugin with the language-agnostic [riff-raff-action](https://github.com/guardian/actions-riff-raff)
After this change has been merged and tested it might be good to consider some follow-on tasks:
- Remove the sbt plugin `riff-raff-artifact` from the project
- Update to java 11
- Migrate to cdk
After the GitHub …

Migrate build to GitHub actions

---

README.md

Following #47  this change updates the readme to include details about how the project is built and how it can be deployed.

Update readme with build and deploy info

---

build.sbt
project/plugins.sbt

Now this project uses [actions-riff-raff](https://github.com/guardian/actions-riff-raff) we can remove the use of the sbt plugin.
Actions-riff-raff is probably a more simple choice going forward: it allows us to abstract as much of the build/deploy config from our code + build.sbt as possible.
I triggered the build workflow manually, the action was [successful](https://github.com/guardian/live-app-versions/actions/runs/5357829216). This means that the project compile, artefacts generated and uploaded to the riff-raff s3 bucket.
I was able to successfully deploy the corresponding build into CODE:
I triggered one of the lambdas via the AWS console. The invocation was successful:
I think the above steps validate that the build/deploy process still works as expected without affecting the …

Remove sbt-riffraff-artifact plugin

---

cfn.yaml
src/main/scala/com/gu/okhttp/SharedClient.scala

The server alerts channel is getting a little noisy because, over the past couple of months, we've seen an increase in the number of failures of the ios-deployments lambda:
This PR aims to address these failures by increasing the http client's timeout. We checked the api [docs](https://developer.apple.com/documentation/appstoreconnectapi) and didn't find any mention of why the api wouldn't return a response. If the response was being throttled we would expect to be returned a [429](https://developer.apple.com/documentation/appstoreconnectapi/identifying_rate_limits) instead of the response hanging. 
The okhttp library has a default timeout of [10 seconds](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/connect-timeout/) and through experimentation on our local …

Increase app store connect api timeout

---

cfn.yaml
src/main/scala/com/gu/okhttp/SharedClient.scala

In [this](https://github.com/guardian/live-app-versions/pull/51) PR we increased the timeout of the http client to try and reduce the number of timeout exceptions we were seeing. We've just seen an error in PROD:
As a result I think it's worth increasing again. When we did local testing before the response time varied a lot so I don't think there's a huge amount of harm in increasing the timeout even further.
I've doubled both the http client timeouts and the lambda timeout accordingly.
After this has been merged to PROD we'll continue to monitor the mobile server alerts channel, if we see more timeout errors we may like to re-assess our approach.

Increase the api timeout (again)

---

build.sbt

Unfortunately these updates broke the logger in the lambda. See screenshot below. Reverting for now.

Revert "chore(deps): AWS dependency updates"

---

build.sbt

The Snyk scanning identified a high severity vulnerability on `io.netty:netty-codec-http2`.  The vulnerability has been fixed in version `4.1.100.Final`
This PR bumps the netty dependencies to `4.1.100.Final` to fix it.
All unit tests passed.

Bump netty to fix snyk vulnerability

---

build.sbt
project/build.properties
project/plugins.sbt

Reverts guardian/live-app-versions#65
We saw the lambda return errors:

Revert "chore(deps): Non-AWS dependency updates"

---

src/main/scala/com/gu/appstoreconnectapi/AppStoreConnectApi.scala
src/main/scala/com/gu/config/Config.scala

The [iosdeployments lambda](https://github.com/guardian/live-app-versions/blob/main/src/main/scala/com/gu/iosdeployments/Lambda.scala) runs every 5 minutes to carry out a number of actions related to new deployments of the app. One of the tasks it carries out is [distributing builds to external beta testers](https://github.com/guardian/live-app-versions/blob/41bbbe6a4e38879f7be1dfcf8ba2ef434319ed06/src/main/scala/com/gu/iosdeployments/Lambda.scala#L49), which we have defined in TestFlight. A new group of testers has been added to TestFlight since this lambda was first created ([Guardian Staff](https://appstoreconnect.apple.com/apps/409128287/testflight/groups/3f5f1a35-dd71-4e11-8643-b20d0939c071)), and this PR ensures that this group is added automatically to new beta builds, in addition …

Add Guardian Staff to beta tester groups

---

src/main/scala/com/gu/appstoreconnectapi/AppStoreConnectApi.scala
src/main/scala/com/gu/config/Config.scala

In preparation for Xcode 16, we want to set up a separate beta build pipeline. The purpose of this is to allow us to test what is in main from the latest Xcode before it is released in September. More details on the process are in [this document](https://docs.google.com/document/d/1KT7PMhYluSJ700yTtxI_PXlty9tYA4myLQxVIp46dNc/edit). 
We plan to ship Xcode 16 betas to External Testers 2 only, which means we need to stop that group being added automatically to our regular Xcode 15 betas. Once this experimental phase is over and we've fully moved over to Xcode, we will revert this PR and have both tester groups automatically added to each new beta build again. 
The next beta build is due to go out on Monday evening. Once it has been approved by Apple, the iosdeployments lambda should …

Temporarily pause automatically distributing to External Testers 2

---

build.sbt

This adds the latest jackson library explicitly to address a vulnerability introduced by an older version of this. 
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

Fix vulnerability in jackson core

---

src/main/scala/com/gu/appstoreconnectapi/AppStoreConnectApi.scala
src/main/scala/com/gu/config/Config.scala

As part of the investigation into the incorrect articles bug on iOS, we recruited beta users to 3 new 'bug verification' tester groups. We no longer need them to help us verify the cause of the bug, so we want to start distributing the regular beta builds to them on the same schedule as External Testers 1. 
For now, we're keeping External Testers 2 as a group that we can submit experimental builds to, as per https://github.com/guardian/live-app-versions/pull/90. 
When the next beta build goes out, the iosdeployments lambda should automatically add External Testers 1, External Testers 3, External Testers 4, External Testers 5, and Guardian Staff to that build, but not External Testers 2.

Add External Testers 3, 4, 5 to iosdeployments lambda

---

.github/workflows/build.yml
.tool-versions

This adds the https://github.com/guardian/setup-scala action to make sbt available in the ci environment.

Add setup-scala GHA

---

src/main/scala/com/gu/appstoreconnectapi/AppStoreConnectApi.scala
src/main/scala/com/gu/config/Config.scala

In https://github.com/guardian/live-app-versions/pull/90, we temporarily paused distributing our regular beta builds to one of our external beta tester groups, so that we could use that group specifically for testing Xcode 16 builds. That work is now complete, so we want to re-enable the automatic distribution of beta builds to group 2. 
The next beta build is due to go out tonight. Once it has been approved by Apple, the iosdeployments lambda should automatically add External Testers 2 to that build, as well as External Testers 1, 3, 4, 5 and Guardian Staff.

iOS: Restore automatic release of betas to External Testers 2

---

src/main/scala/com/gu/githubapi/Conversion.scala
src/main/scala/com/gu/githubapi/GitHubApi.scala

On Monday 27th January at 7pm, the ios-deployments lambda started reporting a [decoding failure](https://logs.gutools.co.uk/s/mobile/app/r/s/jc4NV):
[Cloudwatch](https://eu-west-1.console.aws.amazon.com/lambda/home?region=eu-west-1#/functions/ios-deployments-PROD?subtab=stateMachines&tab=monitoring) also clearly showed the failures in this lambda starting at the same time:
The consequence of this was that beta builds uploaded to App Store Connect via a GitHub Action were not being submitted to Apple for review, or distributed to external testers.
The exact error being reported was:
```
[main] INFO com.gu.okhttp.SharedClient$ - Received successful response from GitHub API. Response code: 200
[main] ERROR com.gu.iosdeployments.Lambda$ - Failed to check deployment status due to: …
```

Use Long instead of Int to model databaseId

---

build.sbt

This upgrades the netty libraries to address these security notifications: https://github.com/guardian/live-app-versions/security/dependabot/1 and https://github.com/guardian/live-app-versions/security/dependabot/2
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

Upgrade versions of netty

---

README.md

Update readme to highlight that the code lambda should be turned off promptly after testing as letting it run overnight hit the google api limit and affected the android beta app release.

update readme about code lambda testing
